blank_issues_enabled: false
contact_links:
  - name: Prismic Community Forum
    url: https://community.prismic.io
    about: Please use Prismic community forum for issues or questions directly related to Prismic.
